type Relation = {
  slug: string;
  count: number;
  name: string;
};

export type TCar = {
  markId: string;
  folderId: string;
  modificationId: string;
  complectationName: string;
  bodyType: string;
  wheel: string;
  color: string;
  metallic: string;
  availability: string;
  custom: string;
  state: string;
  ownersNumber: string;
  run: number;
  year: number;
  registryYear: number;
  currency: string;
  vin: string;
  price: number;
  creditDiscount: number;
  insuranceDiscount: number;
  tradeinDiscount: number;
  maxDiscount: number;
  extras: string;
  images: {
    image: string[];
  };
  video: string;
  bookingAllowed: boolean;
  pts: string;
  uniqueId: number;
  exchange: string;
  techParamId: number;
  engineVolume: number;
  enginePower: string;
  engineType: string;
  gearbox: string;
  drive: string;
  modelName: string;
  generationName: string;
  markCyrillicName: string;
  modelCyrillicName: string;
  offerType: string;
  updatedAt: string;
  generationRel: Relation;
  brandRel: Relation;
  modelRel: Relation;
  imagesAmount: number;
  engineTypeEng: string;
  enginePowerNum: number;
  bodyTypeEng: string;
  ownersNumberNum: number;
  colorEng: string;
  gearboxEng: string;
};
